BAT_START_COLUMNS = [
    ("ProjectionSource", "string"),
    ("Rank", "int"),
    ("Position", "string"),
    ("Name", "string"),
    ("MlbamId", "int"),
    ("FangraphsId", "int"),
    ("FantraxId", "string"),
    ("Age", "int"),
    ("League", "string"),
    ("Team", "string"),
    ("ShortName", "string"),
    ("Status", "string"),
    ("Salary", "currency", 2),
    ("Contract", "int"),
    ("Points", "float", 2),
    ("Pts/G", "float", 2),
    ("PAR", "float", 2),
    ("AuctionValue", "currency", 2),
    ("ContractValue", "currency", 2),
    ("ADP", "float", 2),
    ("G", "int"),
    ("AB", "int"),
    ("PA", "int"),
    ("H", "int"),
    ("1B", "int"),
    ("2B", "int"),
    ("3B", "int"),
    ("HR", "int"),
    ("R", "int"),
    ("RBI", "int"),
    ("BB", "int"),
    ("IBB", "int"),
    ("SO", "int"),
    ("HBP", "int"),
    ("SF", "int"),
    ("SH", "int"),
    ("SB", "int"),
    ("CS", "int"),
    ("AVG", "float", 3),
    ("OBP", "float", 3),
    ("SLG", "float", 3),
    ("OPS", "float", 3),
    ("wOBA", "float", 3),
    ("BB%", "float", 2),
    ("K%", "float", 2),
    ("BB/K", "float", 2),
    ("ISO", "float", 3),
    ("Spd", "float", 2),
    ("BABIP", "float", 3),
    ("wRC", "float", 2),
    ("wRAA", "float", 2),
    ("UZR", "float", 2),
    ("wBsR", "float", 2),
    ("BaseRunning", "float", 2),
    ("WAR", "float", 2),
    ("Off", "float", 2),
    ("Def", "float", 2),
    ("wRC+", "float", 2),
]

PIT_START_COLUMNS = [
    ("ProjectionSource", "string"),
    ("Rank", "int"),
    ("Position", "string"),
    ("Name", "string"),
    ("MlbamId", "int"),
    ("FangraphsId", "int"),
    ("FantraxId", "string"),
    ("Age", "int"),
    ("League", "string"),
    ("Team", "string"),
    ("ShortName", "string"),
    ("Status", "string"),
    ("Salary", "currency", 2),
    ("Contract", "int"),
    ("Points", "float", 2),
    ("Pts/IP", "float", 2),
    ("PAR", "float", 2),
    ("AuctionValue", "currency", 2),
    ("ContractValue", "currency", 2),
    ("ADP", "float", 2),
    ("W", "int"),
    ("L", "int"),
    ("GS", "int"),
    ("G", "int"),
    ("SV", "int"),
    ("HLD", "int"),
    ("IP", "float", 2),
    ("TBF", "int"),
    ("H", "int"),
    ("R", "int"),
    ("ER", "int"),
    ("HR", "int"),
    ("SO", "int"),
    ("BB", "int"),
    ("HBP", "int"),
    ("ERA", "float", 2),
    ("WHIP", "float", 2),
    ("K/9", "float", 2),
    ("BB/9", "float", 2),
    ("K/BB", "float", 2),
    ("HR/9", "float", 2),
    ("K%", "float", 2),
    ("BB%", "float", 2),
    ("K-BB%", "float", 2),
    ("GB%", "float", 2),
    ("AVG", "float", 2),
    ("BABIP", "float", 2),
    ("LOB%", "float", 2),
    ("FIP", "float", 2),
]
